# DL Lab 1

# Shresht Mishra

# 211020450

In [1]:
import tensorflow as tf

## 2.

In [3]:
t1 = tf.constant([1, 2, 3])
t2 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t3 = tf.constant([[[2,2],[3,3]],[[4,4],[5,5]]])

In [4]:
print(t1)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [5]:
print(t2)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [6]:
print(t3)

tf.Tensor(
[[[2 2]
  [3 3]]

 [[4 4]
  [5 5]]], shape=(2, 2, 2), dtype=int32)


In [7]:
zero_1d = tf.zeros([3])
zero_2d = tf.zeros([3,3],tf.int32)
zero_3d = tf.zeros([3,3,3])

In [8]:
print(zero_1d)

tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)


In [9]:
print(zero_2d)

tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]], shape=(3, 3), dtype=int32)


In [10]:
print(zero_3d)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(3, 3, 3), dtype=float32)


In [11]:
ones_1d = tf.ones([2])
ones_2d = tf.ones([2,2])
ones_3d = tf.ones([2,2,2])

In [12]:
print(ones_1d)

tf.Tensor([1. 1.], shape=(2,), dtype=float32)


In [13]:
print(ones_2d)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [14]:
print(ones_3d)

tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


In [15]:
fill_1d = tf.fill([3], 5)
fill_2d = tf.fill([3,3], 5)
fill_3d = tf.fill([3,3,3], 5)

In [16]:
print(fill_1d)

tf.Tensor([5 5 5], shape=(3,), dtype=int32)


In [17]:
print(fill_2d)

tf.Tensor(
[[5 5 5]
 [5 5 5]
 [5 5 5]], shape=(3, 3), dtype=int32)


In [18]:
print(fill_3d)

tf.Tensor(
[[[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]], shape=(3, 3, 3), dtype=int32)


## 3.

In [19]:
tf.rank(t1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [20]:
tf.rank(zero_3d)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [21]:
tf.rank(fill_2d)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## 4.

In [22]:
tf.shape(t3)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 2])>

In [23]:
tf.shape(zero_2d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3])>

## 5.

In [24]:
t4 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
t5 = [[[1, 1], [2, 2]],
     [[3, 3], [4, 4]]]

In [25]:
tf.reshape(t4, [3, 3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [26]:
tf.reshape(t5, [2, 4])

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 1, 2, 2],
       [3, 3, 4, 4]])>

In [27]:
t7 = tf.constant([[[1, 1, 1], [2, 2, 2]],
                 [[3, 3, 3], [4, 4, 4]],
                 [[5, 5, 5], [6, 6, 6]]])

## 6.

In [28]:
print(tf.slice(t7, [1, 0, 0], [1, 1, 3]) )

tf.Tensor([[[3 3 3]]], shape=(1, 1, 3), dtype=int32)


In [29]:
print(tf.slice(t7, [1, 0, 0], [1, 2, 3]) )

tf.Tensor(
[[[3 3 3]
  [4 4 4]]], shape=(1, 2, 3), dtype=int32)


## 7.

In [30]:
matmul_result = tf.matmul(t2, zero_2d)

In [31]:
print(matmul_result)

tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]], shape=(3, 3), dtype=int32)


In [32]:
add_result = tf.add(t2, fill_2d)

In [33]:
print(add_result)

tf.Tensor(
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]], shape=(3, 3), dtype=int32)


In [34]:
subtract_result = tf.subtract(t2, fill_2d)

In [35]:
print(subtract_result)

tf.Tensor(
[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]], shape=(3, 3), dtype=int32)


In [36]:
transpose_result = tf.transpose(t3)

In [37]:
print(transpose_result)

tf.Tensor(
[[[2 4]
  [3 5]]

 [[2 4]
  [3 5]]], shape=(2, 2, 2), dtype=int32)


## 8.

In [38]:
constant_result = t1*2

In [39]:
print(constant_result)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [40]:
initial_value = [1.0, 2.0]
variable_tensor = tf.Variable(initial_value)

In [41]:
variable_tensor.assign(variable_tensor * 2)
print(variable_tensor.numpy())

[2. 4.]


In [42]:
data = tf.data.Dataset.from_tensor_slices([[1, 2, 3], [4, 5, 6]])
iterator = iter(data)
batch = next(iterator)
output = batch * 3
print(output.numpy())

[3 6 9]


## 9.

In [43]:
tf.compat.v1.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [44]:
x = tf.constant([2, 3, 4], dtype=tf.float32, name="x")
y = tf.constant([5, 6, 7], dtype=tf.float32, name="y")
result = tf.multiply(x, y, name="result")

In [45]:
with tf.compat.v1.Session() as sess:
    output = sess.run(result)
    print(output)

[10. 18. 28.]


## 10.

In [2]:
data = [
    (1.0, 2.0),
    (2.0, 3.0),
    (3.0, 4.0),
    (4.0, 5.0),
    (5.0, 6.0)
]
features = [x for x, y in data]
labels = [y for x, y in data]
dataset = tf.data.Dataset.from_tensor_slices((features, labels))
batch_size = 2
dataset = dataset.shuffle(buffer_size=len(data)).batch(batch_size)
for batch in dataset:
    batch_features, batch_labels = batch
    print("Batch Features:", batch_features.numpy())
    print("Batch Labels:", batch_labels.numpy())

Batch Features: [3. 5.]
Batch Labels: [4. 6.]
Batch Features: [4. 2.]
Batch Labels: [5. 3.]
Batch Features: [1.]
Batch Labels: [2.]


# 11.

In [3]:
numpy_iterator = dataset.as_numpy_iterator()
for batch_features, batch_labels in numpy_iterator:
    print("Batch Features (NumPy):", batch_features)
    print("Batch Labels (NumPy):", batch_labels)

Batch Features (NumPy): [2. 1.]
Batch Labels (NumPy): [3. 2.]
Batch Features (NumPy): [3. 4.]
Batch Labels (NumPy): [4. 5.]
Batch Features (NumPy): [5.]
Batch Labels (NumPy): [6.]


In [4]:
def transform_fn(feature, label):
    return feature * 2, label * 3

In [5]:
transformed_dataset = dataset.map(transform_fn)
for batch_features, batch_labels in transformed_dataset:
    print("Transformed Batch Features:", batch_features.numpy())
    print("Transformed Batch Labels:", batch_labels.numpy())

Transformed Batch Features: [8. 4.]
Transformed Batch Labels: [15.  9.]
Transformed Batch Features: [ 2. 10.]
Transformed Batch Labels: [ 6. 18.]
Transformed Batch Features: [6.]
Transformed Batch Labels: [12.]


In [6]:
num_samples = dataset.cardinality().numpy()
print("Number of Samples:", num_samples)

Number of Samples: 3
